name:                elemalg
version:             0.1.0.0
author:              "Ralph Moeritz"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  elemalg-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elemalg
